=== schioler/event-reg/EventParent/EventBase/src/main/data/event-schema-0.6.xsd
<?xml version="1.0" ?>
<xsd:schema targetNamespace="http://www.schioler.dk/xsd/event" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
   xmlns:event="http://www.schioler.dk/xsd/event" elementFormDefault="qualified" attributeFormDefault="unqualified" version="0.6">
   
   <xsd:complexType name="event-template">
   	<xsd:attribute name="name" type="xsd:string"></xsd:attribute>
   	<xsd:attribute name="short-name" type="xsd:string"></xsd:attribute>
   	<xsd:attribute name="unit" type="xsd:string" use="required"></xsd:attribute>
   	<xsd:attribute name="dose" type="xsd:string" use="required"></xsd:attribute>
   	<xsd:attribute name="description" type="xsd:string" />
  		<xsd:attribute name="is-favorite" type="xsd:boolean" default="false"></xsd:attribute>
   </xsd:complexType>
   <xsd:complexType name="event-type">
      <xsd:sequence maxOccurs="unbounded" minOccurs="0">
         <xsd:element name="event-template" type="event:event-template"></xsd:element>
      </xsd:sequence>
      <xsd:attribute name="name" type="xsd:string" use="required"></xsd:attribute>
      <xsd:attribute name="short-name" type="xsd:string" use="required"></xsd:attribute>
      <xsd:attribute name="description" type="xsd:string" use="optional"></xsd:attribute>
   </xsd:complexType>
   
   <xsd:element name="root">
      <xsd:complexType>
         <xsd:sequence maxOccurs="unbounded" minOccurs="1">
            <xsd:element name="event-type" type="event:event-type"></xsd:element>
         </xsd:sequence>
      </xsd:complexType>
   </xsd:element>
</xsd:schema>

=== schioler/event-reg/EventParent/EventWar/src/main/data/event-base-data.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.schioler.dk/xsd/event"
   xsi:schemaLocation="http://www.schioler.dk/xsd/event ./event-schema-0.6.xsd">
   <event-type name="Medicin-parkinson" short-name="MEDICIN-PARK">
      <event-template name="Sinemet 25/100" dose="25/100" unit="mg" short-name="SINE_25100"/>
      <event-template name="Sinemet halv" dose="23.5/50" unit="mg" short-name="SINE-EXT"/>
      <event-template name="Ropinirol 8mg" dose="8" unit="mg" short-name="ROPI-8"/>
      <event-template name="Ropinirol 8+2mg" dose="10" unit="mg" short-name="ROPI-8+2"/>
      <event-template name="Ongentsys" dose="50" unit="mg" short-name="ONGS-50"/>
      <event-template name="Madopar-Quick 62,5" dose="62.5" unit="mg" short-name="MADO-QUICK-62"/>
      <event-template name="Entacapone" dose="200" unit="mg" short-name="ENTACAP-200"/>
   </event-type>
   <event-type name="Medicin-anden" short-name="MEDICIN-ANDEN">
      <event-template name="Betmiga 25mg" dose="25" unit="mg" short-name="BETM-25"/>
      <event-template name="Imozop 7.5mg" dose="7.5" unit="mg" short-name="IMOZ-7.5"/>
      <event-template name="Melatonin 2mg" dose="2" unit="mg" short-name="MELATONIN"/>
      <event-template name="Microlax" dose="" unit="" short-name="MICROLAX"/>
      <event-template name="Kodipar 1stk" dose="500/30.6" unit="mg" short-name="KODIPAR_1STK"/>
      <event-template name="Kodipar + Panodil" dose="" unit="mg" short-name="KODIPAR_PANO"/>
      <event-template name="Ipren" dose="200" unit="mg" short-name="IPREN"/>
      <event-template name="Ipren" dose="500" unit="mg" short-name="IPREN"/>
   </event-type>
   <event-type name="Behandling" short-name="BEHANDL">
      <event-template name="Fysioterapi - solo" dose="30" unit="minutes" short-name="FYS-SOLO"/>
      <event-template name="Fysioterapi - hold" dose="60" unit="minutes" short-name="FYS-HOLD"/>
      <event-template name="Zoneterapi" dose="70" unit="minutes" short-name="ZONET"/>
      <event-template name="Praktiserende læge" dose="20" unit="minutes" short-name="PRAKTISERENDE"/>
      <event-template name="Massage" dose="15" unit="minutes" short-name="MASSAGE"/>
      <event-template name="Hash" dose="1" unit="sug" short-name="HASH"/>
   </event-type>
   <event-type name="Vitamin" short-name="VITAMIN">
      <event-template name="B12 1mg" dose="1" unit="mg" short-name="B12-1MG"/>
      <event-template name="Multi" dose="10" unit="mg" short-name="MULTI"/>
      <event-template name="Magnesia 2x500" dose="500" unit="mg" short-name="MAGNESIA"/>
      <event-template name="Olivir" dose="" unit="" short-name="OLIVIR-XX"/>
   </event-type>
   <event-type name="Fysik" short-name="FYSIK">
      <event-template name="afføring" dose="STOR" unit="ml" short-name="AFFØR-STOR"/>
      <event-template name="afføring" dose="MLM" unit="ml" short-name="AFFØR-MLM"/>
      <event-template name="afføring" dose="LILLE" unit="ml" short-name="AFFØR-LILLE"/>
      <event-template name="urinering" dose="STOR" unit="ml" short-name="URIN"/>
      <event-template name="urinering" dose="MLM" unit="ml" short-name="URIN"/>
      <event-template name="urinering" dose="LILLE" unit="ml" short-name="URIN"/>
      <event-template name="søvn" dose="4" unit="timer" short-name="SØVN"/>
      <event-template name="Væske-indtag" dose="0.5" unit="liter" short-name="VÆSKE-IND"/>
      <event-template name="Hash" dose="1" unit="drag" short-name="HASH"/>
   </event-type>
   <event-type name="Tilstand" short-name="TILSTAND">
      <event-template name="Fantastic - feeling free" dose="" unit="registration" short-name="STATE-10"/>
      <event-template name="Fantastic" dose="" unit="registration" short-name="STATE-09"/>
      <event-template name="Good - pretty good " dose="" unit="registration" short-name="STATE-08"/>
      <event-template name="Good - can do stuff" dose="" unit="registration" short-name="STATE-07"/>
      <event-template name="Could be better - hesitant on doing stuff" dose="" unit="registration" short-name="STATE-06"/>
      <event-template name="Could be better - too warm, tired, ok movements" dose="" unit="registration" short-name="STATE-05"/>
      <event-template name="Bad - too warm, no energy, reduced agility" dose="" unit="registration" short-name="STATE-04"/>
      <event-template name="Bad - full stop" dose="" unit="registration" short-name="STATE-03"/>
      <event-template name="Bad - want to lie down" dose="" unit="registration" short-name="STATE-02"/>
      <event-template name="Bad - want to Die" dose="" unit="registration" short-name="STATE-01"/>
   </event-type>
</root>
